name: DiscipleBay deployment
on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Install dependency without package lock
      #   run: npm ci

      # - name: Build artifact if present
      #   run: |
      #       npm i --save-dev
      #       npm run build
        
      - name: Archive artefact
        run: 'tar -cvf dist.tar.gz ./'

      - name: SSH copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DISCIPLEBAY_HOST }}
          username: ${{ secrets.DISCIPLEBAY_USERNAME }}
          password: ${{ secrets.DISCIPLEBAY_KEY }}
          port: ${{ secrets.DISCIPLEBAY_KEY_PORT }}
          source: "dist.tar.gz,package.json"
          target: "/home/ubuntu/disciplesBay-api"

      # - name: Untar artefact and remove file
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DISCIPLEBAY_HOST }}
      #     username: ${{ secrets.DISCIPLEBAY_USERNAME }}
      #     key: ${{ secrets.DISCIPLEBAY_KEY }}
      #     port: ${{ secrets.DISCIPLEBAY_KEY_PORT }}
      #     script: |
      #         cd /home/ubuntu/disciplesBay-api
      #         pm2 stop dist/index.js
      #         tar xf dist.tar.gz
      #         rm dist.tar.gz
      #         npm install --only=prod
      #         npm run start

           

     
